In [72]:
! pip install squidpy

Requirement already satisfied: squidpy in /home/r10user3/anaconda3/envs/pyg/lib/python3.8/site-packages (1.2.3)
Requirement already satisfied: matplotlib-scalebar>=0.8.0 in /home/r10user3/anaconda3/envs/pyg/lib/python3.8/site-packages (from squidpy) (0.8.1)
Requirement already satisfied: zarr>=2.6.1 in /home/r10user3/anaconda3/envs/pyg/lib/python3.8/site-packages (from squidpy) (2.15.0)
Requirement already satisfied: scikit-learn>=0.24.0 in /home/r10user3/anaconda3/envs/pyg/lib/python3.8/site-packages (from squidpy) (1.0.1)
Requirement already satisfied: typing-extensions in /home/r10user3/anaconda3/envs/pyg/lib/python3.8/site-packages (from squidpy) (4.4.0)
Requirement already satisfied: leidenalg>=0.8.2 in /home/r10user3/anaconda3/envs/pyg/lib/python3.8/site-packages (from squidpy) (0.9.1)
Requirement already satisfied: scikit-image>=0.19 in /home/r10user3/anaconda3/envs/pyg/lib/python3.8/site-packages (from squidpy) (0.21.0)
Requirement already satisfied: aiohttp>=3.8.1 in /home/r10user3/anaconda3/envs/pyg/lib/python3.8/site-packages (from squidpy) (3.8.1)
Requirement already satisfied: docrep>=0.3.1 in /home/r10user3/anaconda3/envs/pyg/lib/python3.8/site-packages (from squidpy) (0.3.2)
Requirement already satisfied: matplotlib!=3.6.1,>=3.3 in /home/r10user3/anaconda3/envs/pyg/lib/python3.8/site-packages (from squidpy) (3.5.0)
Requirement already satisfied: tifffile!=2022.4.22 in /home/r10user3/anaconda3/envs/pyg/lib/python3.8/site-packages (from squidpy) (2023.4.12)
Requirement already satisfied: networkx>=2.6.0 in /home/r10user3/anaconda3/envs/pyg/lib/python3.8/site-packages (from squidpy) (3.1)
Requirement already satisfied: xarray>=0.16.1 in /home/r10user3/anaconda3/envs/pyg/lib/python3.8/site-packages (from squidpy) (2023.1.0)
Requirement already satisfied: statsmodels>=0.12.0 in /home/r10user3/anaconda3/envs/pyg/lib/python3.8/site-packages (from squidpy) (0.13.5)
Requirement already satisfied: dask-image>=0.5.0 in /home/r10user3/anaconda3/envs/pyg/lib/python3.8/site-packages (from squidpy) (2023.3.0)
Requirement already satisfied: omnipath>=1.0.5 in /home/r10user3/anaconda3/envs/pyg/lib/python3.8/site-packages (from squidpy) (1.0.7)
Requirement already satisfied: tqdm>=4.50.2 in /home/r10user3/anaconda3/envs/pyg/lib/python3.8/site-packages (from squidpy) (4.62.3)
Requirement already satisfied: numpy>=1.21.6 in /home/r10user3/anaconda3/envs/pyg/lib/python3.8/site-packages (from squidpy) (1.21.6)
Requirement already satisfied: Pillow>=8.0.0 in /home/r10user3/anaconda3/envs/pyg/lib/python3.8/site-packages (from squidpy) (9.5.0)
Requirement already satisfied: pandas>=1.5.0 in /home/r10user3/anaconda3/envs/pyg/lib/python3.8/site-packages (from squidpy) (1.5.3)
Requirement already satisfied: fsspec>=2021.11.0 in /home/r10user3/anaconda3/envs/pyg/lib/python3.8/site-packages (from squidpy) (2022.1.0)
Requirement already satisfied: cycler>=0.11.0 in /home/r10user3/.local/lib/python3.8/site-packages (from squidpy) (0.11.0)
Requirement already satisfied: numba<0.56.0,>=0.55.0 in /home/r10user3/anaconda3/envs/pyg/lib/python3.8/site-packages (from squidpy) (0.55.1)
Requirement already satisfied: scanpy>=1.8.0 in /home/r10user3/anaconda3/envs/pyg/lib/python3.8/site-packages (from squidpy) (1.9.1)
Requirement already satisfied: anndata>=0.7.4 in /home/r10user3/anaconda3/envs/pyg/lib/python3.8/site-packages (from squidpy) (0.8.0)
Requirement already satisfied: dask[array]>=2021.02.0 in /home/r10user3/anaconda3/envs/pyg/lib/python3.8/site-packages (from squidpy) (2021.10.0)
Requirement already satisfied: validators>=0.18.2 in /home/r10user3/anaconda3/envs/pyg/lib/python3.8/site-packages (from squidpy) (0.20.0)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /home/r10user3/anaconda3/envs/pyg/lib/python3.8/site-packages (from aiohttp>=3.8.1->squidpy) (4.0.1)
Requirement already satisfied: frozenlist>=1.1.1 in /home/r10user3/anaconda3/envs/pyg/lib/python3.8/site-packages (from aiohttp>=3.8.1->squidpy) (1.2.0)
Requirement already satisfied: charset-normalizer<3.0,>=2.0 in /home/r10user3/anaconda3/envs/pyg/lib/python3.8/site-packages (from aiohttp>=3.8.1->squidpy) (2.0.9)
Requirement already satisfied: yarl<2.0,>=1.0 in /home/r10user3/anaconda3/envs/pyg/lib/python3.8/site-packages (from aiohttp>=3.8.1->squidpy) (1.6.3)
Requirement already satisfied: attrs>=17.3.0 in /home/r10user3/anaconda3/envs/pyg/lib/python3.8/site-packages (from aiohttp>=3.8.1->squidpy) (21.2.0)
Requirement already satisfied: aiosignal>=1.1.2 in /home/r10user3/anaconda3/envs/pyg/lib/python3.8/site-packages (from aiohttp>=3.8.1->squidpy) (1.2.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /home/r10user3/anaconda3/envs/pyg/lib/python3.8/site-packages (from aiohttp>=3.8.1->squidpy) (5.2.0)
Requirement already satisfied: packaging>=20 in /home/r10user3/.local/lib/python3.8/site-packages (from anndata>=0.7.4->squidpy) (21.3)
Requirement already satisfied: scipy>1.4 in /home/r10user3/anaconda3/envs/pyg/lib/python3.8/site-packages (from anndata>=0.7.4->squidpy) (1.10.1)
Requirement already satisfied: natsort in /home/r10user3/anaconda3/envs/pyg/lib/python3.8/site-packages (from anndata>=0.7.4->squidpy) (8.1.0)
Requirement already satisfied: h5py>=3 in /home/r10user3/anaconda3/envs/pyg/lib/python3.8/site-packages (from anndata>=0.7.4->squidpy) (3.7.0)
Requirement already satisfied: pims>=0.4.1 in /home/r10user3/anaconda3/envs/pyg/lib/python3.8/site-packages (from dask-image>=0.5.0->squidpy) (0.6.1)
Requirement already satisfied: cloudpickle>=1.1.1 in /home/r10user3/anaconda3/envs/pyg/lib/python3.8/site-packages (from dask[array]>=2021.02.0->squidpy) (2.0.0)
Requirement already satisfied: partd>=0.3.10 in /home/r10user3/anaconda3/envs/pyg/lib/python3.8/site-packages (from dask[array]>=2021.02.0->squidpy) (1.2.0)
Requirement already satisfied: pyyaml in /home/r10user3/anaconda3/envs/pyg/lib/python3.8/site-packages (from dask[array]>=2021.02.0->squidpy) (5.4.1)
Requirement already satisfied: toolz>=0.8.2 in /home/r10user3/anaconda3/envs/pyg/lib/python3.8/site-packages (from dask[array]>=2021.02.0->squidpy) (0.11.2)
Requirement already satisfied: six in /home/r10user3/.local/lib/python3.8/site-packages (from docrep>=0.3.1->squidpy) (1.16.0)
Requirement already satisfied: igraph<0.11,>=0.10.0 in /home/r10user3/anaconda3/envs/pyg/lib/python3.8/site-packages (from leidenalg>=0.8.2->squidpy) (0.10.2)
Requirement already satisfied: texttable>=1.6.2 in /home/r10user3/anaconda3/envs/pyg/lib/python3.8/site-packages (from igraph<0.11,>=0.10.0->leidenalg>=0.8.2->squidpy) (1.6.7)
Requirement already satisfied: pyparsing>=2.2.1 in /home/r10user3/.local/lib/python3.8/site-packages (from matplotlib!=3.6.1,>=3.3->squidpy) (3.0.9)
Requirement already satisfied: fonttools>=4.22.0 in /home/r10user3/anaconda3/envs/pyg/lib/python3.8/site-packages (from matplotlib!=3.6.1,>=3.3->squidpy) (4.25.0)
Requirement already satisfied: python-dateutil>=2.7 in /home/r10user3/.local/lib/python3.8/site-packages (from matplotlib!=3.6.1,>=3.3->squidpy) (2.8.2)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/r10user3/anaconda3/envs/pyg/lib/python3.8/site-packages (from matplotlib!=3.6.1,>=3.3->squidpy) (1.3.1)
Requirement already satisfied: llvmlite<0.39,>=0.38.0rc1 in /home/r10user3/anaconda3/envs/pyg/lib/python3.8/site-packages (from numba<0.56.0,>=0.55.0->squidpy) (0.38.0)
Requirement already satisfied: setuptools in /home/r10user3/anaconda3/envs/pyg/lib/python3.8/site-packages (from numba<0.56.0,>=0.55.0->squidpy) (58.0.4)
Requirement already satisfied: urllib3>=1.26.0 in /home/r10user3/anaconda3/envs/pyg/lib/python3.8/site-packages (from omnipath>=1.0.5->squidpy) (1.26.7)
Requirement already satisfied: wrapt>=1.12.0 in /home/r10user3/anaconda3/envs/pyg/lib/python3.8/site-packages (from omnipath>=1.0.5->squidpy) (1.14.1)
Requirement already satisfied: inflect>=4.1.0 in /home/r10user3/anaconda3/envs/pyg/lib/python3.8/site-packages (from omnipath>=1.0.5->squidpy) (6.0.4)
Requirement already satisfied: requests>=2.24.0 in /home/r10user3/anaconda3/envs/pyg/lib/python3.8/site-packages (from omnipath>=1.0.5->squidpy) (2.26.0)
Requirement already satisfied: pydantic>=1.9.1 in /home/r10user3/anaconda3/envs/pyg/lib/python3.8/site-packages (from inflect>=4.1.0->omnipath>=1.0.5->squidpy) (1.10.9)
Requirement already satisfied: pytz>=2020.1 in /home/r10user3/anaconda3/envs/pyg/lib/python3.8/site-packages (from pandas>=1.5.0->squidpy) (2021.3)
Requirement already satisfied: locket in /home/r10user3/anaconda3/envs/pyg/lib/python3.8/site-packages/locket-0.2.1-py3.8.egg (from partd>=0.3.10->dask[array]>=2021.02.0->squidpy) (0.2.1)
Requirement already satisfied: imageio in /home/r10user3/anaconda3/envs/pyg/lib/python3.8/site-packages (from pims>=0.4.1->dask-image>=0.5.0->squidpy) (2.31.1)
Requirement already satisfied: slicerator>=0.9.8 in /home/r10user3/anaconda3/envs/pyg/lib/python3.8/site-packages (from pims>=0.4.1->dask-image>=0.5.0->squidpy) (1.1.0)
Requirement already satisfied: idna<4,>=2.5 in /home/r10user3/.local/lib/python3.8/site-packages (from requests>=2.24.0->omnipath>=1.0.5->squidpy) (3.3)
Requirement already satisfied: certifi>=2017.4.17 in /home/r10user3/anaconda3/envs/pyg/lib/python3.8/site-packages (from requests>=2.24.0->omnipath>=1.0.5->squidpy) (2022.12.7)
Requirement already satisfied: joblib in /home/r10user3/.local/lib/python3.8/site-packages (from scanpy>=1.8.0->squidpy) (1.1.0)
Requirement already satisfied: umap-learn>=0.3.10 in /home/r10user3/anaconda3/envs/pyg/lib/python3.8/site-packages (from scanpy>=1.8.0->squidpy) (0.5.3)
Requirement already satisfied: patsy in /home/r10user3/anaconda3/envs/pyg/lib/python3.8/site-packages (from scanpy>=1.8.0->squidpy) (0.5.3)
Requirement already satisfied: seaborn in /home/r10user3/anaconda3/envs/pyg/lib/python3.8/site-packages (from scanpy>=1.8.0->squidpy) (0.11.2)
Requirement already satisfied: session-info in /home/r10user3/anaconda3/envs/pyg/lib/python3.8/site-packages (from scanpy>=1.8.0->squidpy) (1.0.0)
Requirement already satisfied: PyWavelets>=1.1.1 in /home/r10user3/anaconda3/envs/pyg/lib/python3.8/site-packages (from scikit-image>=0.19->squidpy) (1.1.1)
Requirement already satisfied: lazy_loader>=0.2 in /home/r10user3/anaconda3/envs/pyg/lib/python3.8/site-packages (from scikit-image>=0.19->squidpy) (0.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /home/r10user3/anaconda3/envs/pyg/lib/python3.8/site-packages (from scikit-learn>=0.24.0->squidpy) (3.0.0)
Requirement already satisfied: pynndescent>=0.5 in /home/r10user3/anaconda3/envs/pyg/lib/python3.8/site-packages (from umap-learn>=0.3.10->scanpy>=1.8.0->squidpy) (0.5.7)
Requirement already satisfied: decorator>=3.4.0 in /home/r10user3/anaconda3/envs/pyg/lib/python3.8/site-packages (from validators>=0.18.2->squidpy) (4.4.2)
Requirement already satisfied: fasteners in /home/r10user3/anaconda3/envs/pyg/lib/python3.8/site-packages (from zarr>=2.6.1->squidpy) (0.18)
Requirement already satisfied: asciitree in /home/r10user3/anaconda3/envs/pyg/lib/python3.8/site-packages (from zarr>=2.6.1->squidpy) (0.3.3)
Requirement already satisfied: numcodecs>=0.10.0 in /home/r10user3/anaconda3/envs/pyg/lib/python3.8/site-packages (from zarr>=2.6.1->squidpy) (0.11.0)
Requirement already satisfied: entrypoints in /home/r10user3/anaconda3/envs/pyg/lib/python3.8/site-packages (from numcodecs>=0.10.0->zarr>=2.6.1->squidpy) (0.4)
Requirement already satisfied: stdlib-list in /home/r10user3/anaconda3/envs/pyg/lib/python3.8/site-packages (from session-info->scanpy>=1.8.0->squidpy) (0.8.0)

In [73]:
import pandas as pd
import numpy as np
import anndata as ad
from scipy.sparse import csr_matrix

spot_coord = pd.read_csv("/data2/r10user3/Spatial_Gene_Cell_Ratio/data/human_lung_cell2location/WSA_LngSP8759312/spots.csv", index_col=0)
spot_coord['X'] = spot_coord['X'] / 112
spot_coord['Y'] = spot_coord['Y'] / 112

cell_abundance = pd.read_csv("/data2/r10user3/Spatial_Gene_Cell_Ratio/data/human_lung_cell2location/WSA_LngSP8759312/cell_ratio.csv", index_col=0)
cell_abundance = cell_abundance.loc[spot_coord.index]

location = np.matrix(spot_coord.values)
Xdense = np.matrix(cell_abundance.values)

X = csr_matrix(Xdense, dtype=np.float32)
adata = ad.AnnData(X, obsm={"spatial": location})
adata

AnnData object with n_obs × n_vars = 2564 × 80
    obsm: 'spatial'

In [74]:
adata.obs_names = list(cell_abundance.index)
adata.var_names = list(cell_abundance.columns)
adata

AnnData object with n_obs × n_vars = 2564 × 80
    obsm: 'spatial'

In [75]:
import squidpy as sq

sq.gr.spatial_neighbors(adata, coord_type="generic", spatial_key="spatial")
adata

/home/r10user3/anaconda3/envs/pyg/lib/python3.8/site-packages/sklearn/utils/validation.py:585: FutureWarning: np.matrix usage is deprecated in 1.0 and will raise a TypeError in 1.2. Please convert to a numpy array with np.asarray. For more information see: https://numpy.org/doc/stable/reference/generated/numpy.matrix.html
  warnings.warn(

AnnData object with n_obs × n_vars = 2564 × 80
    uns: 'spatial_neighbors'
    obsm: 'spatial'
    obsp: 'spatial_connectivities', 'spatial_distances'

In [76]:
sq.gr.spatial_autocorr(adata, mode="moran")

In [77]:
adata.uns["moranI"].head(10)

,I,pval_norm,var_norm,pval_norm_fdr_bh
q05cell_abundance_w_sf_NK_CD16hi,0.812455,0.0,0.00013,0.0
q05cell_abundance_w_sf_NK_CD11d,0.802487,0.0,0.00013,0.0
q05cell_abundance_w_sf_CD4_TRM,0.799560,0.0,0.00013,0.0
q05cell_abundance_w_sf_gdT,0.795093,0.0,0.00013,0.0
q05cell_abundance_w_sf_CD4_EM_Effector,0.794764,0.0,0.00013,0.0
q05cell_abundance_w_sf_ILC,0.794412,0.0,0.00013,0.0
q05cell_abundance_w_sf_CD8_EM,0.789481,0.0,0.00013,0.0
q05cell_abundance_w_sf_SMG_Duct,0.786928,0.0,0.00013,0.0
q05cell_abundance_w_sf_T_reg,0.783730,0.0,0.00013,0.0
q05cell_abundance_w_sf_B_naive,0.780201,0.0,0.00013,0.0

In [78]:
df  = pd.DataFrame(adata.uns["moranI"])
df

,I,pval_norm,var_norm,pval_norm_fdr_bh
q05cell_abundance_w_sf_NK_CD16hi,0.812455,0.000000e+00,0.00013,0.000000e+00
q05cell_abundance_w_sf_NK_CD11d,0.802487,0.000000e+00,0.00013,0.000000e+00
q05cell_abundance_w_sf_CD4_TRM,0.799560,0.000000e+00,0.00013,0.000000e+00
q05cell_abundance_w_sf_gdT,0.795093,0.000000e+00,0.00013,0.000000e+00
q05cell_abundance_w_sf_CD4_EM_Effector,0.794764,0.000000e+00,0.00013,0.000000e+00
...,...,...,...,...
q05cell_abundance_w_sf_Chondrocyte,0.268113,0.000000e+00,0.00013,0.000000e+00
q05cell_abundance_w_sf_Macro_CHIT1,0.195916,0.000000e+00,0.00013,0.000000e+00
q05cell_abundance_w_sf_Fibro_alveolar,0.147083,0.000000e+00,0.00013,0.000000e+00
q05cell_abundance_w_sf_AT1,0.132477,0.000000e+00,0.00013,0.000000e+00
q05cell_abundance_w_sf_AT2,0.092857,1.110223e-16,0.00013,1.110223e-16

In [79]:
# load multi-task GNN cell pearson list
import pickle

with open('/data2/r10user3/Spatial_Gene_Cell_Ratio/code/pearson_log/cell_gene_2layersimpleGNN_lr1e-4_cell_pearson_list.pkl', 'rb') as f:
    multi_cell_pearson_list = pickle.load(f)
df['pearson'] = multi_cell_pearson_list
df

,I,pval_norm,var_norm,pval_norm_fdr_bh,pearson
q05cell_abundance_w_sf_NK_CD16hi,0.812455,0.000000e+00,0.00013,0.000000e+00,0.164479
q05cell_abundance_w_sf_NK_CD11d,0.802487,0.000000e+00,0.00013,0.000000e+00,0.140642
q05cell_abundance_w_sf_CD4_TRM,0.799560,0.000000e+00,0.00013,0.000000e+00,0.313251
q05cell_abundance_w_sf_gdT,0.795093,0.000000e+00,0.00013,0.000000e+00,0.418429
q05cell_abundance_w_sf_CD4_EM_Effector,0.794764,0.000000e+00,0.00013,0.000000e+00,0.358119
...,...,...,...,...,...
q05cell_abundance_w_sf_Chondrocyte,0.268113,0.000000e+00,0.00013,0.000000e+00,0.241010
q05cell_abundance_w_sf_Macro_CHIT1,0.195916,0.000000e+00,0.00013,0.000000e+00,0.482241
q05cell_abundance_w_sf_Fibro_alveolar,0.147083,0.000000e+00,0.00013,0.000000e+00,0.379403
q05cell_abundance_w_sf_AT1,0.132477,0.000000e+00,0.00013,0.000000e+00,0.468492
q05cell_abundance_w_sf_AT2,0.092857,1.110223e-16,0.00013,1.110223e-16,0.501955

In [82]:
df.sort_values('I', ascending=False).to_csv('/data2/r10user3/Spatial_Gene_Cell_Ratio/code/raw_data/MoranI.csv')